### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by saantifranco** [Batta32/VanTrackDatabase#1]
- Driver:
-> calif_acum es un acumlado, hace falta que tenga decimales? 
-Empresa:
-> usu_id: por qué la empresa tiene una FK a un user?
-Horario:
-> Por qué tiene sólo un inicio? Cómo se terminan todos los horarios con esa única información? No es medio raro que un horario tenga o pueda tener todos los días que incluye pero una única hora?
-> Se me ocurre que podríamos cargar de antemano horarios fijos (Ej: Todas las horas para todos los días fraccionadas cada 5 minutos y que al momento de crear un viaje la empresa seleccione entre esos horarios). Entonces quedaría una tabla estática con ((24*60)/5)*7 = 2016 registros. Y cubrimos un espectro super amplio de horarios y no dejamos que carguen cualquier cosa.
-> Adicionalmente estamos las reservas tienen una referencia a un servicio y el servicio a un horario, entonces si el horario tiene muchos días: ¿Para qué día estoy reservando?. Idem para viaje, ¿Qué día viajó?
Recorrido:
-> Por qué tiene un 'Precio' y otras tablas un 'Precio final'? Hay alguna diferencia?

**Comment by Batta32** [comment]
> Driver:
 calif_acum es un acumlado, hace falta que tenga decimales? 

Le puse decimales debido a que no se definio los valores de calificacion (asumi que puede entrar calificacion en decimal, aun asi se puede cambiar si se pasa a valores enteros)

>Empresa:
usu_id: por qué la empresa tiene una FK a un user?

Debido a que se genera automaticamente el usuario de esa empresa, lo mismo pasa con el conductor. Cuando se genera una empresa, se le genera el usuario. Cuando la empresa genera un conductor, se le genera el usuario.. para unificar la tabla de usuarios con toda la informacion de empresa, conductor y usuario final.

>-Horario:
Por qué tiene sólo un inicio? Cómo se terminan todos los horarios con esa única información? No es medio raro que un horario tenga o pueda tener todos los días que incluye pero una única hora?
Se me ocurre que podríamos cargar de antemano horarios fijos (Ej: Todas las horas para todos los días fraccionadas cada 5 minutos y que al momento de crear un viaje la empresa seleccione entre esos horarios). Entonces quedaría una tabla estática con ((24*60)/5)*7 = 2016 registros. Y cubrimos un espectro super amplio de horarios y no dejamos que carguen cualquier cosa.
Adicionalmente estamos las reservas tienen una referencia a un servicio y el servicio a un horario, entonces si el horario tiene muchos días: ¿Para qué día estoy reservando?. Idem para viaje, ¿Qué día viajó?

Fixed, lo hablamos el otro dia

@saantifranco
